name: 'run BiliExp'

on:
  schedule:
    - cron: '0 4 * * *' #中午12:00执行，时间与其他脚本有依赖关系如无必要请勿修改
  watch:
    types: started
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
      with: 
        ref: BiliExp-Actions

    - name: 配置用户信息(一定要填写secrets)
      run: echo '${{ secrets.biliconfig }}' > ./config/config.json

    - name: 安装aiohttp
      run: |
          sudo pip3 install setuptools
          sudo pip3 install aiohttp

    - name: 执行B站经验脚本BiliExp.py
      run: python3 BiliExp.py
